name: Automatisation des tests

on:
  push:
    branches:
      - main

jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup CMake
        run: sudo apt-get install cmake
        
      - name: Compilation et tests
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make

  Run_Tests:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup CMake
        run: sudo apt-get install cmake

      - name: Exécuter les tests
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          ctest --output-on-failure --parallel 4  # Exécute les tests en parallèle avec 4 threads
